[build]
publish = "public"
command = "hugo mod get github.com/nunocoracao/blowfish/v2@main && hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.148.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
